<a href="https://colab.research.google.com/github/KeremAydin98/opencv-exercises-in-python/blob/main/1_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

ARRAYS

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mylist=[1,2,3,4,5]

In [ ]:
mylist

[1, 2, 3, 4, 5]

In [ ]:
type(mylist)

list

In [ ]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [ ]:
type(mylist)

list

MATRIX

In [ ]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
myarray=np.arange(0,100)

In [ ]:
new_array=myarray.reshape(10,10)

In [ ]:
new_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
new_array[0,1]

1

In [ ]:
new_array[4,6]

46

In [ ]:
new_array[:,2].reshape(10,-1)

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [ ]:
new_array[:,2]=0

In [ ]:
new_array

array([[ 0,  1,  0,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0, 13, 14, 15, 16, 17, 18, 19],
       [20, 21,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31,  0, 33, 34, 35, 36, 37, 38, 39],
       [40, 41,  0, 43, 44, 45, 46, 47, 48, 49],
       [50, 51,  0, 53, 54, 55, 56, 57, 58, 59],
       [60, 61,  0, 63, 64, 65, 66, 67, 68, 69],
       [70, 71,  0, 73, 74, 75, 76, 77, 78, 79],
       [80, 81,  0, 83, 84, 85, 86, 87, 88, 89],
       [90, 91,  0, 93, 94, 95, 96, 97, 98, 99]])